## Config file
lr:                     3e-4 # Initial learning rate
epochs:                 1 # Number of epochs to train the model 
number_classes:         2 # Number of classes in the target dataset
batch_size_tr:          2 # Batch size for train
batch_size_va:          2 # Batch size for validation 
saved_model:            './checkpoints/weights_deepcrack.model'
saved_model_final:      './checkpoints/weights_deepcrack_final.model'
path_to_tradata:        '/Users/mustafa/Desktop/Courses/ComputerVision/Project/Imagenius/DeepCrack/train' #path to dataset (./Crack500/train)
path_to_valdata:        '/Users/mustafa/Desktop/Courses/ComputerVision/Project/Imagenius/DeepCrack/test'  #path to dataset (./Crack500/test)
path_to_testdata:       '/Users/mustafa/Desktop/Courses/ComputerVision/Project/Imagenius/DeepCrack/test'  #path to dataset (./Crack500/val)
patience:               6 # number of epochs without improvement to do before finishing training early.reduce the lr
progress_p:             0.5 # value between 0-1 shows the number of time we need to report training progress in each epoch
pretrained:             0 # load the previously trained weight or no value should either 1 or 0
loss_filename:         'loss_log.txt'
save_result:           './results/' # path to save results
# Below are added later
nhead:                 8 # number of heads in the transformer
num_layers:           6 # number of layers in the transformer